#ifndef _DATATYPE_H_
#define _DATATYPE_H_

/*ENUM type for DVR*/
enum EVENT_CODE {
    PIPELINE_SWITCH_MODE_DAILY,
    PIPELINE_SWITCH_MODE_EMERGENCY,
    PIPELINE_SWITCH_MODE_REMOTE,
    PIPELINE_SWITCH_MODE_LOWPOWER,
    PIPELINE_SWITCH_MODE_RECORD,
    PIPELINE_SWITCH_MODE_CAPTURE,
    PIPELINE_SWITCH_MODE__MAX_NUMBER,
};

enum WorkMode{
    PIPELINE_WORK_MODE_DAILY,
    PIPELINE_WORK_MODE_EMERGENCY,
    PIPELINE_WORK_MODE_REMOTE,
    PIPELINE_WORK_MODE_LOWPOWER,
    PIPELINE_WORK_MODE_RECORD,
    PIPELINE_WORK_MODE_CAPTURE,
    PIPELINE_WORK_MODE_ANY,
};

enum WORK_MODE_CHANGE_CODE{
    PIPELINE_WORKMODE_DAILY_TO_EMERGENCY,
    PIPELINE_WORKMODE_DAILY_TO_CAPTURE,
    PIPELINE_WORKMODE_DAILY_TO_RECORD,
    PIPELINE_WORKMODE_DAILY_TO_REMOTE,
    PIPELINE_WORKMODE_REMOTE_TO_EMERGENCY,
    PIPELINE_WORKMODE_REMOTE_TO_CAPTURE,
    PIPELINE_WORKMODE_REMOTE_TO_RECORD,
    PIPELINE_WORKMODE_REMOTE_TO_DAILY,
    PIPELINE_WORKMODE_RECORD_TO_EMERGENCY,
    PIPELINE_WORKMODE_RECORD_TO_CAPRURE,
    PIPELINE_WORKMODE_DRECORD_TO_DAILY,
    PIPELINE_WORKMODE_CAPTURE_TO_EMERGENCY,
    PIPELINE_WORKMODE_CAPTURE_TO_RECORD,
    PIPELINE_WORKMODE_CAPTURE_TO_DAILY,
};

/*ENUM type for DVR end*/

#endif
