#ifndef _COMMON_H_
#define _COMMON_H_
#include <pthread.h>


#define MSG_KEY_BIND "bind"
#define MSG_KEY_DESTINATION "destination"
#define MSG_KEY_ORIGIN "origin"
#define MSG_KEY_RECEIVER "receiver"
#define MSG_KEY_OPID "functionid"

#define SOCKET_PATH "/tmp/socket_path"
#define CONNECT_CLIENT_MAX 5

#define SOCKET_MSG_LENGTH 1024


typedef int t_int;
typedef unsigned int t_uint;

/*ENUM type for DVR*/
enum EVENT_CODE {
    PIPELINE_SWITCH_MODE_DAILY,
    PIPELINE_SWITCH_MODE_EMERGENCY,
    PIPELINE_SWITCH_MODE_REMOTE,
    PIPELINE_SWITCH_MODE_LOWPOWER,
    PIPELINE_SWITCH_MODE_RECORD,
    PIPELINE_SWITCH_MODE_CAPTURE,
    PIPELINE_SWITCH_MODE__MAX_NUMBER,
};

enum WorkMode{
    PIPELINE_WORK_MODE_DAILY,
    PIPELINE_WORK_MODE_EMERGENCY,
    PIPELINE_WORK_MODE_REMOTE,
    PIPELINE_WORK_MODE_LOWPOWER,
    PIPELINE_WORK_MODE_RECORD,
    PIPELINE_WORK_MODE_CAPTURE,
    PIPELINE_WORK_MODE_ANY,
};

enum WORK_MODE_CHANGE_CODE{
    PIPELINE_WORKMODE_DAILY_TO_EMERGENCY,
    PIPELINE_WORKMODE_DAILY_TO_CAPTURE,
    PIPELINE_WORKMODE_DAILY_TO_RECORD,
    PIPELINE_WORKMODE_DAILY_TO_REMOTE,
    PIPELINE_WORKMODE_REMOTE_TO_EMERGENCY,
    PIPELINE_WORKMODE_REMOTE_TO_CAPTURE,
    PIPELINE_WORKMODE_REMOTE_TO_RECORD,
    PIPELINE_WORKMODE_REMOTE_TO_DAILY,
    PIPELINE_WORKMODE_RECORD_TO_EMERGENCY,
    PIPELINE_WORKMODE_RECORD_TO_CAPRURE,
    PIPELINE_WORKMODE_DRECORD_TO_DAILY,
    PIPELINE_WORKMODE_CAPTURE_TO_EMERGENCY,
    PIPELINE_WORKMODE_CAPTURE_TO_RECORD,
    PIPELINE_WORKMODE_CAPTURE_TO_DAILY,
};

/*ENUM type for DVR end*/
enum ERROR_CODE {
    E_OPERATION_ERROR_NONE,
    E_OPERATION_ERROR_PARA,
    E_OPERATION_ERROR_NOT_INIT,
    E_OPERATION_ERROR_THREAD_CREATE,
    E_OPERATION_ERROR_THREAD_NUM_MAX,
    E_OPERATION_ERROR_FUNC_CALL,
    E_OPERATION_ERROR_SOCKET_CONNECTION,
    E_OPERATION_ERROR_WRITE_SOCKET,
    E_OPERATION_ERROR_UNKNOW,
};
enum THREAD_NUM {
    E_THREAD_NUM_1,
    E_THREAD_NUM_2,
    E_THREAD_NUM_3,
    E_THREAD_NUM_4,
    E_THREAD_NUM_MAX,
};
class ThreadData
{
public:
    t_int thread_num;
    pthread_t id[E_THREAD_NUM_MAX];
    void *ctx;
};

#endif
