#ifndef _COMMON_H_
#define _COMMON_H_
enum ERROR_CODE {
    E_OPERATION_ERROR_NONE,
    E_OPERATION_ERROR_PARA,
    E_OPERATION_ERROR_NOT_INIT,
    E_OPERATION_ERROR_THREAD_CREATE,
    E_OPERATION_ERROR_THREAD_NUM_MAX,
    E_OPERATION_ERROR_FUNC_CALL,
    E_OPERATION_ERROR_SOCKET_CONNECTION,
    E_OPERATION_ERROR_WRITE_SOCKET,
    E_OPERATION_ERROR_UNKNOW,
};
enum OPERATION_CODE_ENGINE {
    E_ENGINE_FUNCTION_START_NEW_THREAD,
    E_ENGINE_FUNCTION_ON_THREAD_TERMINATE,
    E_ENGINE_FUNCTION_MAX_NUMBER,
};
#endif
